version: "3.8"

services:
  mysql-db:
    image: mysql
    container_name: mysql_database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=transaction
